### ISSUE TITLE
License please

### ISSUE THREAD

**Issue by hopeseekr** [hemant347/IntToWords#1]
Could you please license this under the MIT License so that my project can use this project? Thank you.

**Comment by hemant347** [comment]
License added. You can use it now.

**Comment by hopeseekr** [comment]
Awesome! Thanks for the fast response! I usually dread it will takes months / maybe never to resolve these sort of things.

InToWords is now being used in the utilphp project: 
https://github.com/brandonwamboldt/utilphp/blob/master/CONTRIBUTORS.md
